package com.hbsd.service.business;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.hbsd.bean.business.TbPlanQuery;
import org.apache.log4j.Logger;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


import com.hbsd.bean.business.TbPlan;
import com.hbsd.bean.business.TbPlanContext;
import com.hbsd.mapper.business.TbPlanMapper;
import com.hbsd.model.business.TbPlanModel;
import com.hbsd.service.sys.BaseService;

/**
 * <br>
 * <b>功能：</b>TbPlanService<br>
 */
@Service("tbPlanService")
public class TbPlanService<T> extends BaseService<T> {
    private final static Logger log = Logger.getLogger(TbPlanService.class);


    @Autowired
    private TbPlanMapper<T> mapper;

    public int queryStatus(int planId) {
        return mapper.queryStatus(planId);
    }

    public TbPlanMapper<T> getMapper() {
        return mapper;
    }

    public List<TbPlanQuery> planQueryList(Integer userId) {
        return mapper.queryPlans(userId);
    }

    public HSSFWorkbook export(List<TbPlan> list, List<TbPlanContext> tbPlanContext) throws IOException {
        File fi = new File("D:\\周计划模板.xls");
        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(fi));
        //读取excel模板
        HSSFWorkbook wb = new HSSFWorkbook(fs);
        //读取了模板内所有sheet内容
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow row = sheet.getRow((int) 0);
        HSSFRow row2 = sheet.getRow((int) 0);
        HSSFRow row3 = sheet.getRow((int) 0);

        HSSFFont font2 = wb.createFont();
        font2.setFontName("仿宋_GB2312");
        font2.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);//粗体显示
        font2.setFontHeightInPoints((short) 11);

        HSSFCellStyle style = wb.createCellStyle();
        style.setAlignment(HSSFCellStyle.ALIGN_CENTER);
        style.setVerticalAlignment(XSSFCellStyle.VERTICAL_CENTER);
        style.setBorderBottom(HSSFCellStyle.BORDER_THIN); //下边框
        style.setBorderLeft(HSSFCellStyle.BORDER_THIN);//左边框
        style.setBorderTop(HSSFCellStyle.BORDER_THIN);//上边框
        style.setBorderRight(HSSFCellStyle.BORDER_THIN);//右边框
        style.setFont(font2);
        for (int i = 0; i < list.size(); i++) {
            TbPlan student = list.get(i);
            TbPlanContext tbcontext = tbPlanContext.get(i);
            if (student.getPlan_type() == 10) {
                if (i >= 1) {
                    int q = 6;
                    int w = q + (8 * i);
                    HSSFRow rows = sheet.createRow((int) w);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(w, w, (short) 1, (short) 5);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) w + 1);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(w + 1, w + 1, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(w + 1, w + 1, (short) 4, (short) 5);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) w + 2);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(w + 2, w + 2, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(w + 2, w + 2, (short) 4, (short) 5);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) w + 3);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) w + 4);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) w + 5);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) w + 6);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) w + 7);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(w + 4, w + 7, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(w + 4, w + 7, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    int j = 0;
                    int g = j + (8 * i);
                    row = sheet.getRow(g + 7);
                    row2 = sheet.getRow(g + 6);
                    row3 = sheet.getRow(g + 10);
                } else {
                    HSSFRow rows = sheet.createRow((int) 6);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(6, 6, (short) 1, (short) 5);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) 7);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(7, 7, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(7, 7, (short) 4, (short) 5);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) 8);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(8, 8, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(8, 8, (short) 4, (short) 5);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) 9);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) 10);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) 11);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) 12);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) 13);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(10, 13, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(10, 13, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    row = sheet.getRow(7);
                    row2 = sheet.getRow(6);
                    row3 = sheet.getRow(10);
                }
                row.getCell(1).setCellValue(student.getManagername());
                row2.getCell(1).setCellValue(student.getProject_name());
                row3.getCell(1).setCellValue(tbcontext.getData_value());
                row3.getCell(0).setCellValue(tbcontext.getNickName());
                row3.getCell(2).setCellValue(student.getPlan_task());
                row3.getCell(3).setCellValue(student.getPlan_expect_result());
                row3.getCell(4).setCellValue(student.getPlan_expect_enddate());
                row3.getCell(5).setCellValue(student.getPlan_expect_time());

            }
        }
        return wb;
    }

    public HSSFWorkbook excelsum(List<TbPlan> list, List<TbPlanContext> tbPlanContext) throws FileNotFoundException, IOException {
        File fi = new File("D:\\周总结模板.xls");
        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(fi));
        //读取excel模板
        HSSFWorkbook wb = new HSSFWorkbook(fs);
        //读取了模板内所有sheet内容
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow row = sheet.getRow((int) 0);
        HSSFRow row2 = sheet.getRow((int) 0);
        HSSFRow row3 = sheet.getRow((int) 0);

        HSSFFont font2 = wb.createFont();
        font2.setFontName("仿宋_GB2312");
        font2.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);//粗体显示
        font2.setFontHeightInPoints((short) 11);

        HSSFCellStyle style = wb.createCellStyle();
        style.setAlignment(HSSFCellStyle.ALIGN_CENTER);
        style.setVerticalAlignment(XSSFCellStyle.VERTICAL_CENTER);
        style.setBorderBottom(HSSFCellStyle.BORDER_THIN); //下边框
        style.setBorderLeft(HSSFCellStyle.BORDER_THIN);//左边框
        style.setBorderTop(HSSFCellStyle.BORDER_THIN);//上边框
        style.setBorderRight(HSSFCellStyle.BORDER_THIN);//右边框
        style.setFont(font2);
        for (int i = 0; i < list.size(); i++) {

            TbPlan student = list.get(i);
            TbPlanContext tbcontext = tbPlanContext.get(i);
            if (student.getPlan_type() == 10) {
                if (i >= 1) {
                    int q = 2;
                    int w = q + (8 * i);
                    HSSFRow rows = sheet.createRow((int) w);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    HSSFCell cells5 = rows.createCell(6);
                    HSSFCell cells6 = rows.createCell(7);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    cells5.setCellStyle(style);
                    cells6.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(w, w, (short) 1, (short) 7);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) w + 1);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    HSSFCell cellw9 = rows2.createCell(6);
                    HSSFCell cellw10 = rows2.createCell(7);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);
                    cellw9.setCellStyle(style);
                    cellw10.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(w + 1, w + 1, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(w + 1, w + 1, (short) 4, (short) 7);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) w + 2);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(w + 2, w + 2, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(w + 2, w + 2, (short) 4, (short) 7);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) w + 3);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFCell cellm4 = rows4.createCell(6);
                    cellm4.setCellValue("实际用时");
                    cellm4.setCellStyle(style);
                    HSSFCell cellq4 = rows4.createCell(7);
                    cellq4.setCellValue("完成情况");
                    cellq4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) w + 4);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFCell cellm5 = rows5.createCell(6);
                    cellm5.setCellValue("");
                    cellm5.setCellStyle(style);
                    HSSFCell cellq5 = rows5.createCell(7);
                    cellq5.setCellValue("");
                    cellq5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) w + 5);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFCell cellm6 = rows6.createCell(6);
                    cellm6.setCellValue("");
                    cellm6.setCellStyle(style);
                    HSSFCell cellq6 = rows6.createCell(7);
                    cellq6.setCellValue("");
                    cellq6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) w + 6);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFCell cellm7 = rows7.createCell(6);
                    cellm7.setCellValue("");
                    cellm7.setCellStyle(style);
                    HSSFCell cellq7 = rows7.createCell(7);
                    cellq7.setCellValue("");
                    cellq7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) w + 7);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    HSSFCell cellm8 = rows8.createCell(6);
                    cellm8.setCellValue("");
                    cellm8.setCellStyle(style);
                    HSSFCell cellq8 = rows8.createCell(7);
                    cellq8.setCellValue("");
                    cellq8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(w + 4, w + 7, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(w + 4, w + 7, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    int j = 0;
                    int g = j + (8 * i);
                    row = sheet.getRow(g + 3);
                    row2 = sheet.getRow(g + 2);
                    row3 = sheet.getRow(g + 6);
                } else {
                    HSSFRow rows = sheet.createRow((int) 2);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    HSSFCell cells5 = rows.createCell(6);
                    HSSFCell cells6 = rows.createCell(7);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    cells5.setCellStyle(style);
                    cells6.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(2, 2, (short) 1, (short) 7);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) 3);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    HSSFCell cellw9 = rows2.createCell(6);
                    HSSFCell cellw10 = rows2.createCell(7);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);
                    cellw9.setCellStyle(style);
                    cellw10.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(3, 3, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(3, 3, (short) 4, (short) 7);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) 4);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(4, 4, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(4, 4, (short) 4, (short) 7);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) 5);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFCell cellm4 = rows4.createCell(6);
                    cellm4.setCellValue("实际用时");
                    cellm4.setCellStyle(style);
                    HSSFCell cellq4 = rows4.createCell(7);
                    cellq4.setCellValue("完成情况");
                    cellq4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) 6);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFCell cellm5 = rows5.createCell(6);
                    cellm5.setCellValue("");
                    cellm5.setCellStyle(style);
                    HSSFCell cellq5 = rows5.createCell(7);
                    cellq5.setCellValue("");
                    cellq5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) 7);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFCell cellm6 = rows6.createCell(6);
                    cellm6.setCellValue("");
                    cellm6.setCellStyle(style);
                    HSSFCell cellq6 = rows6.createCell(7);
                    cellq6.setCellValue("");
                    cellq6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) 8);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFCell cellm7 = rows7.createCell(6);
                    cellm7.setCellValue("");
                    cellm7.setCellStyle(style);
                    HSSFCell cellq7 = rows7.createCell(7);
                    cellq7.setCellValue("");
                    cellq7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) 9);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    HSSFCell cellm8 = rows8.createCell(6);
                    cellm8.setCellValue("");
                    cellm8.setCellStyle(style);
                    HSSFCell cellq8 = rows8.createCell(7);
                    cellq8.setCellValue("");
                    cellq8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(6, 9, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(6, 9, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    row = sheet.getRow(3);
                    row2 = sheet.getRow(2);
                    row3 = sheet.getRow(6);
                }
                row.createCell(1).setCellValue(student.getNickName());
                row2.createCell(1).setCellValue(student.getProject_name());
                row3.createCell(1).setCellValue(tbcontext.getData_value());
                row3.createCell(0).setCellValue(tbcontext.getNickName());
                row3.createCell(2).setCellValue(student.getPlan_task());
                row3.createCell(3).setCellValue(student.getPlan_expect_result());
                row3.createCell(4).setCellValue(student.getPlan_reality_enddate());
                row3.createCell(5).setCellValue(student.getPlan_expect_time());
                row3.createCell(6).setCellValue(student.getPlan_reality_time());
                row3.createCell(7).setCellValue(student.getPlan_reality_result());

            }
        }

        return wb;
    }


    public HSSFWorkbook Export(List<TbPlan> list, List<TbPlanContext> tbPlanContext) throws IOException {
        File fi = new File("D:\\周计划模板.xls");
        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(fi));
        //读取excel模板
        HSSFWorkbook wb = new HSSFWorkbook(fs);
        //读取了模板内所有sheet内容
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow row = sheet.getRow((int) 0);
        HSSFRow row2 = sheet.getRow((int) 0);
        HSSFRow row3 = sheet.getRow((int) 0);

        HSSFFont font2 = wb.createFont();
        font2.setFontName("仿宋_GB2312");
        font2.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);//粗体显示
        font2.setFontHeightInPoints((short) 11);

        HSSFCellStyle style = wb.createCellStyle();
        style.setAlignment(HSSFCellStyle.ALIGN_CENTER);
        style.setVerticalAlignment(XSSFCellStyle.VERTICAL_CENTER);
        style.setBorderBottom(HSSFCellStyle.BORDER_THIN); //下边框
        style.setBorderLeft(HSSFCellStyle.BORDER_THIN);//左边框
        style.setBorderTop(HSSFCellStyle.BORDER_THIN);//上边框
        style.setBorderRight(HSSFCellStyle.BORDER_THIN);//右边框
        style.setFont(font2);
        for (int i = 0; i < list.size(); i++) {

            TbPlan student = list.get(i);
            TbPlanContext tbcontext = tbPlanContext.get(i);
            if (student.getPlan_type() == 11) {
                if (i >= 1) {
                    int q = 6;
                    int w = q + (8 * i);
                    HSSFRow rows = sheet.createRow((int) w);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(w, w, (short) 1, (short) 5);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) w + 1);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(w + 1, w + 1, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(w + 1, w + 1, (short) 4, (short) 5);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) w + 2);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(w + 2, w + 2, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(w + 2, w + 2, (short) 4, (short) 5);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) w + 3);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) w + 4);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) w + 5);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) w + 6);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) w + 7);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(w + 4, w + 7, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(w + 4, w + 7, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    int j = 0;
                    int g = j + (8 * i);
                    row = sheet.getRow(g + 7);
                    row2 = sheet.getRow(g + 6);
                    row3 = sheet.getRow(g + 10);
                } else {
                    HSSFRow rows = sheet.createRow((int) 6);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(6, 6, (short) 1, (short) 5);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) 7);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(7, 7, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(7, 7, (short) 4, (short) 5);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) 8);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(8, 8, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(8, 8, (short) 4, (short) 5);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) 9);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) 10);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) 11);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) 12);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) 13);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(10, 13, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(10, 13, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    row = sheet.getRow(7);
                    row2 = sheet.getRow(6);
                    row3 = sheet.getRow(10);
                }
                row.getCell(1).setCellValue(student.getManagername());
                row2.getCell(1).setCellValue(student.getProject_name());
                row3.getCell(1).setCellValue(tbcontext.getData_value());
                row3.getCell(0).setCellValue(tbcontext.getNickName());
                row3.getCell(2).setCellValue(student.getPlan_task());
                row3.getCell(3).setCellValue(student.getPlan_expect_result());
                row3.getCell(4).setCellValue(student.getPlan_expect_enddate());
                row3.getCell(5).setCellValue(student.getPlan_expect_time());

            }
        }
        return wb;
    }

    public HSSFWorkbook Excelsum(List<TbPlan> list, List<TbPlanContext> tbPlanContext) throws FileNotFoundException, IOException {
        File fi = new File("D:\\周总结模板.xls");
        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(fi));
        //读取excel模板
        HSSFWorkbook wb = new HSSFWorkbook(fs);
        //读取了模板内所有sheet内容
        HSSFSheet sheet = wb.getSheetAt(0);
        HSSFRow row = sheet.getRow((int) 0);
        HSSFRow row2 = sheet.getRow((int) 0);
        HSSFRow row3 = sheet.getRow((int) 0);

        HSSFFont font2 = wb.createFont();
        font2.setFontName("仿宋_GB2312");
        font2.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);//粗体显示
        font2.setFontHeightInPoints((short) 11);

        HSSFCellStyle style = wb.createCellStyle();
        style.setAlignment(HSSFCellStyle.ALIGN_CENTER);
        style.setVerticalAlignment(XSSFCellStyle.VERTICAL_CENTER);
        style.setBorderBottom(HSSFCellStyle.BORDER_THIN); //下边框
        style.setBorderLeft(HSSFCellStyle.BORDER_THIN);//左边框
        style.setBorderTop(HSSFCellStyle.BORDER_THIN);//上边框
        style.setBorderRight(HSSFCellStyle.BORDER_THIN);//右边框
        style.setFont(font2);
        for (int i = 0; i < list.size(); i++) {

            TbPlan student = list.get(i);
            TbPlanContext tbcontext = tbPlanContext.get(i);
            if (student.getPlan_type() == 11) {
                if (i >= 1) {
                    int q = 2;
                    int w = q + 8;
                    HSSFRow rows = sheet.createRow((int) w);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    HSSFCell cells5 = rows.createCell(6);
                    HSSFCell cells6 = rows.createCell(7);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    cells5.setCellStyle(style);
                    cells6.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(w, w, (short) 1, (short) 7);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) w + 1);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    HSSFCell cellw9 = rows2.createCell(6);
                    HSSFCell cellw10 = rows2.createCell(7);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);
                    cellw9.setCellStyle(style);
                    cellw10.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(w + 1, w + 1, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(w + 1, w + 1, (short) 4, (short) 7);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) w + 2);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(w + 2, w + 2, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(w + 2, w + 2, (short) 4, (short) 7);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) w + 3);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFCell cellm4 = rows4.createCell(6);
                    cellm4.setCellValue("实际用时");
                    cellm4.setCellStyle(style);
                    HSSFCell cellq4 = rows4.createCell(7);
                    cellq4.setCellValue("完成情况");
                    cellq4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) w + 4);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFCell cellm5 = rows5.createCell(6);
                    cellm5.setCellValue("");
                    cellm5.setCellStyle(style);
                    HSSFCell cellq5 = rows5.createCell(7);
                    cellq5.setCellValue("");
                    cellq5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) w + 5);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFCell cellm6 = rows6.createCell(6);
                    cellm6.setCellValue("");
                    cellm6.setCellStyle(style);
                    HSSFCell cellq6 = rows6.createCell(7);
                    cellq6.setCellValue("");
                    cellq6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) w + 6);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFCell cellm7 = rows7.createCell(6);
                    cellm7.setCellValue("");
                    cellm7.setCellStyle(style);
                    HSSFCell cellq7 = rows7.createCell(7);
                    cellq7.setCellValue("");
                    cellq7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) w + 7);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    HSSFCell cellm8 = rows8.createCell(6);
                    cellm8.setCellValue("");
                    cellm8.setCellStyle(style);
                    HSSFCell cellq8 = rows8.createCell(7);
                    cellq8.setCellValue("");
                    cellq8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(w + 4, w + 7, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(w + 4, w + 7, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    int j = 0;
                    int g = j + 8;
                    row = sheet.getRow(g + 3);
                    row2 = sheet.getRow(g + 2);
                    row3 = sheet.getRow(g + 6);
                } else {
                    HSSFRow rows = sheet.createRow((int) 2);
                    rows.setHeightInPoints(25);
                    HSSFCell cell = rows.createCell(0);
                    cell.setCellValue("项目名称");
                    cell.setCellStyle(style);
                    HSSFCell cell1 = rows.createCell(1);
                    HSSFCell cells1 = rows.createCell(2);
                    HSSFCell cells2 = rows.createCell(3);
                    HSSFCell cells3 = rows.createCell(4);
                    HSSFCell cells4 = rows.createCell(5);
                    HSSFCell cells5 = rows.createCell(6);
                    HSSFCell cells6 = rows.createCell(7);
                    cell1.setCellValue("");
                    cell1.setCellStyle(style);
                    cells1.setCellStyle(style);
                    cells2.setCellStyle(style);
                    cells3.setCellStyle(style);
                    cells4.setCellStyle(style);
                    cells5.setCellStyle(style);
                    cells6.setCellStyle(style);
                    CellRangeAddress region1 = new CellRangeAddress(2, 2, (short) 1, (short) 7);
                    sheet.addMergedRegion(region1);

                    HSSFRow rows2 = sheet.createRow((int) 3);
                    rows2.setHeightInPoints(15);
                    HSSFCell cell2 = rows2.createCell(0);
                    cell2.setCellValue("项目经理");
                    cell2.setCellStyle(style);
                    HSSFCell cell3 = rows2.createCell(1);
                    HSSFCell cella3 = rows2.createCell(2);
                    cell3.setCellValue("");
                    cella3.setCellStyle(style);
                    cell3.setCellStyle(style);
                    HSSFCell cell4 = rows2.createCell(3);
                    cell4.setCellValue("指导人");
                    cell4.setCellStyle(style);

                    HSSFCell cell8 = rows2.createCell(4);
                    HSSFCell cellw8 = rows2.createCell(5);
                    HSSFCell cellw9 = rows2.createCell(6);
                    HSSFCell cellw10 = rows2.createCell(7);
                    cell8.setCellValue("");
                    cell8.setCellStyle(style);
                    cellw8.setCellStyle(style);
                    cellw9.setCellStyle(style);
                    cellw10.setCellStyle(style);

                    CellRangeAddress region2 = new CellRangeAddress(3, 3, (short) 1, (short) 2);
                    CellRangeAddress region3 = new CellRangeAddress(3, 3, (short) 4, (short) 7);
                    sheet.addMergedRegion(region2);
                    sheet.addMergedRegion(region3);

                    HSSFRow rows3 = sheet.createRow((int) 4);
                    rows3.setHeightInPoints(15);
                    HSSFCell cell5 = rows3.createCell(0);
                    cell5.setCellValue("建设单位");
                    cell5.setCellStyle(style);
                    HSSFCell cell6 = rows3.createCell(1);
                    HSSFCell celle6 = rows3.createCell(2);
                    cell6.setCellValue("");
                    celle6.setCellStyle(style);
                    cell6.setCellStyle(style);
                    HSSFCell cell7 = rows3.createCell(3);
                    cell7.setCellValue("联系人");
                    cell7.setCellStyle(style);
                    HSSFCell cell9 = rows3.createCell(4);
                    HSSFCell cellr9 = rows3.createCell(5);
                    cell9.setCellValue("");
                    cellr9.setCellStyle(style);
                    cell9.setCellStyle(style);

                    CellRangeAddress region4 = new CellRangeAddress(4, 4, (short) 1, (short) 2);
                    CellRangeAddress region5 = new CellRangeAddress(4, 4, (short) 4, (short) 7);
                    sheet.addMergedRegion(region4);
                    sheet.addMergedRegion(region5);

                    HSSFRow rows4 = sheet.createRow((int) 5);
                    rows4.setHeightInPoints(15);
                    HSSFCell cellz4 = rows4.createCell(0);
                    cellz4.setCellValue("项目成员");
                    cellz4.setCellStyle(style);
                    HSSFCell cellx4 = rows4.createCell(1);
                    cellx4.setCellValue("人员类型");
                    cellx4.setCellStyle(style);
                    HSSFCell cellc4 = rows4.createCell(2);
                    cellc4.setCellValue("工作任务");
                    cellc4.setCellStyle(style);
                    HSSFCell cellv4 = rows4.createCell(3);
                    cellv4.setCellValue("结果定义");
                    cellv4.setCellStyle(style);
                    HSSFCell cellb4 = rows4.createCell(4);
                    cellb4.setCellValue("结束日期");
                    cellb4.setCellStyle(style);
                    HSSFCell celln4 = rows4.createCell(5);
                    celln4.setCellValue("时间	");
                    celln4.setCellStyle(style);
                    HSSFCell cellm4 = rows4.createCell(6);
                    cellm4.setCellValue("实际用时");
                    cellm4.setCellStyle(style);
                    HSSFCell cellq4 = rows4.createCell(7);
                    cellq4.setCellValue("完成情况");
                    cellq4.setCellStyle(style);
                    HSSFRow rows5 = sheet.createRow((int) 6);
                    rows5.setHeightInPoints(25);
                    HSSFCell cellz5 = rows5.createCell(0);
                    cellz5.setCellValue("");
                    cellz5.setCellStyle(style);
                    HSSFCell cellx5 = rows5.createCell(1);
                    cellx5.setCellValue("");
                    cellx5.setCellStyle(style);
                    HSSFCell cellc5 = rows5.createCell(2);
                    cellc5.setCellValue("");
                    cellc5.setCellStyle(style);
                    HSSFCell cellv5 = rows5.createCell(3);
                    cellv5.setCellValue("");
                    cellv5.setCellStyle(style);
                    HSSFCell cellb5 = rows5.createCell(4);
                    cellb5.setCellValue("");
                    cellb5.setCellStyle(style);
                    HSSFCell celln5 = rows5.createCell(5);
                    celln5.setCellValue("");
                    celln5.setCellStyle(style);
                    HSSFCell cellm5 = rows5.createCell(6);
                    cellm5.setCellValue("");
                    cellm5.setCellStyle(style);
                    HSSFCell cellq5 = rows5.createCell(7);
                    cellq5.setCellValue("");
                    cellq5.setCellStyle(style);
                    HSSFRow rows6 = sheet.createRow((int) 7);
                    rows6.setHeightInPoints(45);
                    HSSFCell cellz6 = rows6.createCell(0);
                    cellz6.setCellValue("");
                    cellz6.setCellStyle(style);
                    HSSFCell cellx6 = rows6.createCell(1);
                    cellx6.setCellValue("");
                    cellx6.setCellStyle(style);
                    HSSFCell cellc6 = rows6.createCell(2);
                    cellc6.setCellValue("");
                    cellc6.setCellStyle(style);
                    HSSFCell cellv6 = rows6.createCell(3);
                    cellv6.setCellValue("");
                    cellv6.setCellStyle(style);
                    HSSFCell cellb6 = rows6.createCell(4);
                    cellb6.setCellValue("");
                    cellb6.setCellStyle(style);
                    HSSFCell celln6 = rows6.createCell(5);
                    celln6.setCellValue("");
                    celln6.setCellStyle(style);
                    HSSFCell cellm6 = rows6.createCell(6);
                    cellm6.setCellValue("");
                    cellm6.setCellStyle(style);
                    HSSFCell cellq6 = rows6.createCell(7);
                    cellq6.setCellValue("");
                    cellq6.setCellStyle(style);
                    HSSFRow rows7 = sheet.createRow((int) 8);
                    rows7.setHeightInPoints(25);
                    HSSFCell cellz7 = rows7.createCell(0);
                    cellz7.setCellValue("");
                    cellz7.setCellStyle(style);
                    HSSFCell cellx7 = rows7.createCell(1);
                    cellx7.setCellValue("");
                    cellx7.setCellStyle(style);
                    HSSFCell cellc7 = rows7.createCell(2);
                    cellc7.setCellValue("");
                    cellc7.setCellStyle(style);
                    HSSFCell cellv7 = rows7.createCell(3);
                    cellv7.setCellValue("");
                    cellv7.setCellStyle(style);
                    HSSFCell cellb7 = rows7.createCell(4);
                    cellb7.setCellValue("");
                    cellb7.setCellStyle(style);
                    HSSFCell celln7 = rows7.createCell(5);
                    celln7.setCellValue("");
                    celln7.setCellStyle(style);
                    HSSFCell cellm7 = rows7.createCell(6);
                    cellm7.setCellValue("");
                    cellm7.setCellStyle(style);
                    HSSFCell cellq7 = rows7.createCell(7);
                    cellq7.setCellValue("");
                    cellq7.setCellStyle(style);
                    HSSFRow rows8 = sheet.createRow((int) 9);
                    rows8.setHeightInPoints(25);
                    HSSFCell cellz8 = rows8.createCell(0);
                    cellz8.setCellValue("");
                    cellz8.setCellStyle(style);
                    HSSFCell cellx8 = rows8.createCell(1);
                    cellx8.setCellValue("");
                    cellx8.setCellStyle(style);
                    HSSFCell cellc8 = rows8.createCell(2);
                    cellc8.setCellValue("");
                    cellc8.setCellStyle(style);
                    HSSFCell cellv8 = rows8.createCell(3);
                    cellv8.setCellValue("");
                    cellv8.setCellStyle(style);
                    HSSFCell cellb8 = rows8.createCell(4);
                    cellb8.setCellValue("");
                    cellb8.setCellStyle(style);
                    HSSFCell celln8 = rows8.createCell(5);
                    celln8.setCellValue("");
                    celln8.setCellStyle(style);
                    HSSFCell cellm8 = rows8.createCell(6);
                    cellm8.setCellValue("");
                    cellm8.setCellStyle(style);
                    HSSFCell cellq8 = rows8.createCell(7);
                    cellq8.setCellValue("");
                    cellq8.setCellStyle(style);
                    CellRangeAddress region6 = new CellRangeAddress(6, 9, (short) 0, (short) 0);
                    sheet.addMergedRegion(region6);
                    CellRangeAddress region7 = new CellRangeAddress(6, 9, (short) 1, (short) 1);
                    sheet.addMergedRegion(region7);
                    row = sheet.getRow(3);
                    row2 = sheet.getRow(2);
                    row3 = sheet.getRow(6);
                }
                row.createCell(1).setCellValue(student.getNickName());
                row2.createCell(1).setCellValue(student.getProject_name());
                row3.createCell(1).setCellValue(tbcontext.getData_value());
                row3.createCell(0).setCellValue(tbcontext.getNickName());
                row3.createCell(2).setCellValue(student.getPlan_task());
                row3.createCell(3).setCellValue(student.getPlan_expect_result());
                row3.createCell(4).setCellValue(student.getPlan_reality_enddate());
                row3.createCell(5).setCellValue(student.getPlan_expect_time());
                row3.createCell(6).setCellValue(student.getPlan_reality_time());
                row3.createCell(7).setCellValue(student.getPlan_reality_result());

            }
        }

        return wb;
    }

    public int savePlanChange(String planChange,Integer planContextId){
        return mapper.updatePlanChangeContext(planChange,planContextId);
    }
}
