package com.hbsd.bean.business;

import java.util.Date;

public class TbCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.check_user_id
     *
     * @mbg.generated
     */
    private Integer checkUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.submit_user_id
     *
     * @mbg.generated
     */
    private Integer submitUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.submit_time
     *
     * @mbg.generated
     */
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.check_time
     *
     * @mbg.generated
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.check_type
     *
     * @mbg.generated
     */
    private Byte checkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.check_comment
     *
     * @mbg.generated
     */
    private String checkComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.check_status
     *
     * @mbg.generated
     */
    private Byte checkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_check.context_id
     *
     * @mbg.generated
     */
    private Integer contextId;

//申请人名字
    private String checkUserName;
//审核人名字
    private String submitUserName;
//变更类型
    private String checkTypeName;
//变更内容
    private String deferContent;
//  变更状态名字
    private String checkStatusName;

    public String getCheckStatusName() {
        return checkStatusName;
    }

    public void setCheckStatusName(String checkStatusName) {
        this.checkStatusName = checkStatusName;
    }

    public String getCheckUserName() {
        return checkUserName;
    }

    public void setCheckUserName(String checkUserName) {
        this.checkUserName = checkUserName;
    }

    public String getSubmitUserName() {
        return submitUserName;
    }

    public void setSubmitUserName(String submitUserName) {
        this.submitUserName = submitUserName;
    }

    public String getCheckTypeName() {
        return checkTypeName;
    }

    public void setCheckTypeName(String checkTypeName) {
        this.checkTypeName = checkTypeName;
    }

    public String getDeferContent() {
        return deferContent;
    }

    public void setDeferContent(String deferContent) {
        this.deferContent = deferContent;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.id
     *
     * @return the value of tb_check.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.id
     *
     * @param id the value for tb_check.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.check_user_id
     *
     * @return the value of tb_check.check_user_id
     *
     * @mbg.generated
     */
    public Integer getCheckUserId() {
        return checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.check_user_id
     *
     * @param checkUserId the value for tb_check.check_user_id
     *
     * @mbg.generated
     */
    public void setCheckUserId(Integer checkUserId) {
        this.checkUserId = checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.submit_user_id
     *
     * @return the value of tb_check.submit_user_id
     *
     * @mbg.generated
     */
    public Integer getSubmitUserId() {
        return submitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.submit_user_id
     *
     * @param submitUserId the value for tb_check.submit_user_id
     *
     * @mbg.generated
     */
    public void setSubmitUserId(Integer submitUserId) {
        this.submitUserId = submitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.submit_time
     *
     * @return the value of tb_check.submit_time
     *
     * @mbg.generated
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.submit_time
     *
     * @param submitTime the value for tb_check.submit_time
     *
     * @mbg.generated
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.check_time
     *
     * @return the value of tb_check.check_time
     *
     * @mbg.generated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.check_time
     *
     * @param checkTime the value for tb_check.check_time
     *
     * @mbg.generated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.check_type
     *
     * @return the value of tb_check.check_type
     *
     * @mbg.generated
     */
    public Byte getCheckType() {
        return checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.check_type
     *
     * @param checkType the value for tb_check.check_type
     *
     * @mbg.generated
     */
    public void setCheckType(Byte checkType) {
        this.checkType = checkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.check_comment
     *
     * @return the value of tb_check.check_comment
     *
     * @mbg.generated
     */
    public String getCheckComment() {
        return checkComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.check_comment
     *
     * @param checkComment the value for tb_check.check_comment
     *
     * @mbg.generated
     */
    public void setCheckComment(String checkComment) {
        this.checkComment = checkComment == null ? null : checkComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.check_status
     *
     * @return the value of tb_check.check_status
     *
     * @mbg.generated
     */
    public Byte getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.check_status
     *
     * @param checkStatus the value for tb_check.check_status
     *
     * @mbg.generated
     */
    public void setCheckStatus(Byte checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_check.context_id
     *
     * @return the value of tb_check.context_id
     *
     * @mbg.generated
     */
    public Integer getContextId() {
        return contextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_check.context_id
     *
     * @param contextId the value for tb_check.context_id
     *
     * @mbg.generated
     */
    public void setContextId(Integer contextId) {
        this.contextId = contextId;
    }
}