package com.hbsd.bean.business;

import java.util.Date;
import java.util.List;

public class TbMeeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.id
     *
     * @mbg.generated
     */
    private Integer id;

    private String meetingName;

    private String typeName;

    public String getMeetingUser() {
        return meetingUser;
    }

    public void setMeetingUser(String meetingUser) {
        this.meetingUser = meetingUser;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getMeetingName() {
        return meetingName;
    }

    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.meeting_create_time
     *
     * @mbg.generated
     */
    private Date meetingCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.meeting_type
     *
     * @mbg.generated
     */
    private Byte meetingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.meeting_user_id
     *
     * @mbg.generated
     */
    private Integer meetingUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.meeting_status
     *
     * @mbg.generated
     */
    private Integer meetingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.meeting_file
     *
     * @mbg.generated
     */
    private String meetingFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting.meeting_context
     *
     * @mbg.generated
     */
    private String meetingContext;

    private String meetingUser;//参会人员



    private List<TbMeetingUser> tbMeetingUser;

// 主持人
    private String tbMeetingHost;
// 记录人
    private String tbMeetingRecorder;
//  会议地点
    private String tbMeetingAddress;
//  遗留问题
    private String tbMeetingProblem;



    public String getTbMeetingHost() {
        return tbMeetingHost;
    }

    public void setTbMeetingHost(String tbMeetingHost) {
        this.tbMeetingHost = tbMeetingHost;
    }

    public String getTbMeetingRecorder() {
        return tbMeetingRecorder;
    }

    public void setTbMeetingRecorder(String tbMeetingRecorder) {
        this.tbMeetingRecorder = tbMeetingRecorder;
    }

    public String getTbMeetingAddress() {
        return tbMeetingAddress;
    }

    public void setTbMeetingAddress(String tbMeetingAddress) {
        this.tbMeetingAddress = tbMeetingAddress;
    }

    public String getTbMeetingProblem() {
        return tbMeetingProblem;
    }

    public void setTbMeetingProblem(String tbMeetingProblem) {
        this.tbMeetingProblem = tbMeetingProblem;
    }

    public List<TbMeetingUser> getTbMeetingUser() {
        return tbMeetingUser;
    }

    public void setTbMeetingUser(List<TbMeetingUser> tbMeetingUser) {
        this.tbMeetingUser = tbMeetingUser;
    }

    /**

     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.id
     *
     * @return the value of tb_meeting.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting.id
     *
     * @param id the value for tb_meeting.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.meeting_create_time
     *
     * @return the value of tb_meeting.meeting_create_time
     *
     * @mbg.generated
     */
    public Date getMeetingCreateTime() {
        return meetingCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting.meeting_create_time
     *
     * @param meetingCreateTime the value for tb_meeting.meeting_create_time
     *
     * @mbg.generated
     */
    public void setMeetingCreateTime(Date meetingCreateTime) {
        this.meetingCreateTime = meetingCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.meeting_type
     *
     * @return the value of tb_meeting.meeting_type
     *
     * @mbg.generated
     */
    public Byte getMeetingType() {
        return meetingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting.meeting_type
     *
     * @param meetingType the value for tb_meeting.meeting_type
     *
     * @mbg.generated
     */
    public void setMeetingType(Byte meetingType) {
        this.meetingType = meetingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.meeting_user_id
     *
     * @return the value of tb_meeting.meeting_user_id
     *
     * @mbg.generated
     */
    public Integer getMeetingUserId() {
        return meetingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting.meeting_user_id
     *
     * @param meetingUserId the value for tb_meeting.meeting_user_id
     *
     * @mbg.generated
     */
    public void setMeetingUserId(Integer meetingUserId) {
        this.meetingUserId = meetingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.meeting_status
     *
     * @return the value of tb_meeting.meeting_status
     *
     * @mbg.generated
     */
    public Integer getMeetingStatus() {
        return meetingStatus;
    }

    public void setMeetingStatus(Integer meetingStatus) {
        this.meetingStatus = meetingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.meeting_file
     *
     * @return the value of tb_meeting.meeting_file
     *
     * @mbg.generated
     */
    public String getMeetingFile() {
        return meetingFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting.meeting_file
     *
     * @param meetingFile the value for tb_meeting.meeting_file
     *
     * @mbg.generated
     */
    public void setMeetingFile(String meetingFile) {
        this.meetingFile = meetingFile == null ? null : meetingFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting.meeting_context
     *
     * @return the value of tb_meeting.meeting_context
     *
     * @mbg.generated
     */
    public String getMeetingContext() {
        return meetingContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting.meeting_context
     *
     * @param meetingContext the value for tb_meeting.meeting_context
     *
     * @mbg.generated
     */
    public void setMeetingContext(String meetingContext) {
        this.meetingContext = meetingContext == null ? null : meetingContext.trim();
    }
}