package com.hbsd.bean.business;

public class TbMeetingUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting_user.meeting_id
     *
     * @mbg.generated
     */
    private Integer meetingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_meeting_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting_user.id
     *
     * @return the value of tb_meeting_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting_user.id
     *
     * @param id the value for tb_meeting_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting_user.meeting_id
     *
     * @return the value of tb_meeting_user.meeting_id
     *
     * @mbg.generated
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting_user.meeting_id
     *
     * @param meetingId the value for tb_meeting_user.meeting_id
     *
     * @mbg.generated
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_meeting_user.user_id
     *
     * @return the value of tb_meeting_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_meeting_user.user_id
     *
     * @param userId the value for tb_meeting_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}