package com.hbsd.bean.business;

public class TbOff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_userid
     *
     * @mbg.generated
     */
    private Integer offUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_projectid
     *
     * @mbg.generated
     */
    private Integer offProjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_begintime
     *
     * @mbg.generated
     */
    private String offBegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_endtime
     *
     * @mbg.generated
     */
    private String offEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_createdate
     *
     * @mbg.generated
     */
    private String offCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_context
     *
     * @mbg.generated
     */
    private String offContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_off.off_hour
     *
     * @mbg.generated
     */
    private Double offHour;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.id
     *
     * @return the value of tb_off.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.id
     *
     * @param id the value for tb_off.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_userid
     *
     * @return the value of tb_off.off_userid
     *
     * @mbg.generated
     */
    public Integer getOffUserid() {
        return offUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_userid
     *
     * @param offUserid the value for tb_off.off_userid
     *
     * @mbg.generated
     */
    public void setOffUserid(Integer offUserid) {
        this.offUserid = offUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_projectid
     *
     * @return the value of tb_off.off_projectid
     *
     * @mbg.generated
     */
    public Integer getOffProjectid() {
        return offProjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_projectid
     *
     * @param offProjectid the value for tb_off.off_projectid
     *
     * @mbg.generated
     */
    public void setOffProjectid(Integer offProjectid) {
        this.offProjectid = offProjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_begintime
     *
     * @return the value of tb_off.off_begintime
     *
     * @mbg.generated
     */
    public String getOffBegintime() {
        return offBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_begintime
     *
     * @param offBegintime the value for tb_off.off_begintime
     *
     * @mbg.generated
     */
    public void setOffBegintime(String offBegintime) {
        this.offBegintime = offBegintime == null ? null : offBegintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_endtime
     *
     * @return the value of tb_off.off_endtime
     *
     * @mbg.generated
     */
    public String getOffEndtime() {
        return offEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_endtime
     *
     * @param offEndtime the value for tb_off.off_endtime
     *
     * @mbg.generated
     */
    public void setOffEndtime(String offEndtime) {
        this.offEndtime = offEndtime == null ? null : offEndtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_createdate
     *
     * @return the value of tb_off.off_createdate
     *
     * @mbg.generated
     */
    public String getOffCreatedate() {
        return offCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_createdate
     *
     * @param offCreatedate the value for tb_off.off_createdate
     *
     * @mbg.generated
     */
    public void setOffCreatedate(String offCreatedate) {
        this.offCreatedate = offCreatedate == null ? null : offCreatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_context
     *
     * @return the value of tb_off.off_context
     *
     * @mbg.generated
     */
    public String getOffContext() {
        return offContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_context
     *
     * @param offContext the value for tb_off.off_context
     *
     * @mbg.generated
     */
    public void setOffContext(String offContext) {
        this.offContext = offContext == null ? null : offContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_off.off_hour
     *
     * @return the value of tb_off.off_hour
     *
     * @mbg.generated
     */
    public Double getOffHour() {
        return offHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_off.off_hour
     *
     * @param offHour the value for tb_off.off_hour
     *
     * @mbg.generated
     */
    public void setOffHour(Double offHour) {
        this.offHour = offHour;
    }
}