package com.hbsd.bean.business;

public class TbOvertime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.overtime_userid
     *
     * @mbg.generated
     */
    private Integer overtimeUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.overtime_context
     *
     * @mbg.generated
     */
    private String overtimeContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.overtime_begintime
     *
     * @mbg.generated
     */
    private String overtimeBegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.overtime_endtime
     *
     * @mbg.generated
     */
    private String overtimeEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.overtime_createdate
     *
     * @mbg.generated
     */
    private String overtimeCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_overtime.overtime_hour
     *
     * @mbg.generated
     */
    private String userName;
    private Double overtimeHour;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.id
     *
     * @return the value of tb_overtime.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.id
     *
     * @param id the value for tb_overtime.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.overtime_userid
     *
     * @return the value of tb_overtime.overtime_userid
     *
     * @mbg.generated
     */
    public Integer getOvertimeUserid() {
        return overtimeUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.overtime_userid
     *
     * @param overtimeUserid the value for tb_overtime.overtime_userid
     *
     * @mbg.generated
     */
    public void setOvertimeUserid(Integer overtimeUserid) {
        this.overtimeUserid = overtimeUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.overtime_context
     *
     * @return the value of tb_overtime.overtime_context
     *
     * @mbg.generated
     */
    public String getOvertimeContext() {
        return overtimeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.overtime_context
     *
     * @param overtimeContext the value for tb_overtime.overtime_context
     *
     * @mbg.generated
     */
    public void setOvertimeContext(String overtimeContext) {
        this.overtimeContext = overtimeContext == null ? null : overtimeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.overtime_begintime
     *
     * @return the value of tb_overtime.overtime_begintime
     *
     * @mbg.generated
     */
    public String getOvertimeBegintime() {
        return overtimeBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.overtime_begintime
     *
     * @param overtimeBegintime the value for tb_overtime.overtime_begintime
     *
     * @mbg.generated
     */
    public void setOvertimeBegintime(String overtimeBegintime) {
        this.overtimeBegintime = overtimeBegintime == null ? null : overtimeBegintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.overtime_endtime
     *
     * @return the value of tb_overtime.overtime_endtime
     *
     * @mbg.generated
     */
    public String getOvertimeEndtime() {
        return overtimeEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.overtime_endtime
     *
     * @param overtimeEndtime the value for tb_overtime.overtime_endtime
     *
     * @mbg.generated
     */
    public void setOvertimeEndtime(String overtimeEndtime) {
        this.overtimeEndtime = overtimeEndtime == null ? null : overtimeEndtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.overtime_createdate
     *
     * @return the value of tb_overtime.overtime_createdate
     *
     * @mbg.generated
     */
    public String getOvertimeCreatedate() {
        return overtimeCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.overtime_createdate
     *
     * @param overtimeCreatedate the value for tb_overtime.overtime_createdate
     *
     * @mbg.generated
     */
    public void setOvertimeCreatedate(String overtimeCreatedate) {
        this.overtimeCreatedate = overtimeCreatedate == null ? null : overtimeCreatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_overtime.overtime_hour
     *
     * @return the value of tb_overtime.overtime_hour
     *
     * @mbg.generated
     */
    public Double getOvertimeHour() {
        return overtimeHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_overtime.overtime_hour
     *
     * @param overtimeHour the value for tb_overtime.overtime_hour
     *
     * @mbg.generated
     */
    public void setOvertimeHour(Double overtimeHour) {
        this.overtimeHour = overtimeHour;
    }
}