package com.hbsd.bean.business;

public class TbPlanUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan_user.plan_id
     *
     * @mbg.generated
     */
    private Integer planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan_user.plan_user_id
     *
     * @mbg.generated
     */
    private Integer planUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_plan_user.plan_user_type
     *
     * @mbg.generated
     */
    private Integer planUserType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan_user.id
     *
     * @return the value of tb_plan_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan_user.id
     *
     * @param id the value for tb_plan_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan_user.plan_id
     *
     * @return the value of tb_plan_user.plan_id
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan_user.plan_id
     *
     * @param planId the value for tb_plan_user.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan_user.plan_user_id
     *
     * @return the value of tb_plan_user.plan_user_id
     *
     * @mbg.generated
     */
    public Integer getPlanUserId() {
        return planUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan_user.plan_user_id
     *
     * @param planUserId the value for tb_plan_user.plan_user_id
     *
     * @mbg.generated
     */
    public void setPlanUserId(Integer planUserId) {
        this.planUserId = planUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_plan_user.plan_user_type
     *
     * @return the value of tb_plan_user.plan_user_type
     *
     * @mbg.generated
     */
    public Integer getPlanUserType() {
        return planUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_plan_user.plan_user_type
     *
     * @param planUserType the value for tb_plan_user.plan_user_type
     *
     * @mbg.generated
     */
    public void setPlanUserType(Integer planUserType) {
        this.planUserType = planUserType;
    }
}