package com.hbsd.bean.business;

import java.util.Date;



/**
 * @Author: Hanfei
 * @Date: 2017/3/22
 * @Company:http://www.hbsddz.com
 * @Project:daily
 * @Class:TbScoreRecord
 */

public class TbScoreRecord {

    private Integer id;

    private Integer year;

    private Integer month;


    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.mark_user_id
     *
     * @mbg.generated
     */
    private Integer markUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.comment
     *
     * @mbg.generated
     */
    private String comment;




    private String username;

    private String markUserName;


    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.id
     *
     * @param id the value for tb_score_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.score
     *
     * @return the value of tb_score_record.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.score
     *
     * @param score the value for tb_score_record.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.user_id
     *
     * @return the value of tb_score_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.user_id
     *
     * @param userId the value for tb_score_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.mark_user_id
     *
     * @return the value of tb_score_record.mark_user_id
     *
     * @mbg.generated
     */
    public Integer getMarkUserId() {
        return markUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.mark_user_id
     *
     * @param markUserId the value for tb_score_record.mark_user_id
     *
     * @mbg.generated
     */
    public void setMarkUserId(Integer markUserId) {
        this.markUserId = markUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.create_time
     *
     * @return the value of tb_score_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.create_time
     *
     * @param createTime the value for tb_score_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.mark_type
     *
     * @return the value of tb_score_record.mark_type
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.comment
     *
     * @return the value of tb_score_record.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.comment
     *
     * @param comment the value for tb_score_record.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMarkUserName() {
        return markUserName;
    }

    public void setMarkUserName(String markUserName) {
        this.markUserName = markUserName;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }
}