package com.hbsd.bean.business;

import java.util.Date;

public class TbTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_user_id
     *
     * @mbg.generated
     */
    private Integer planUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.task_context
     *
     * @mbg.generated
     */
    private String taskContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_expect_result
     *
     * @mbg.generated
     */
    private String planExpectResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_expect_enddate
     *
     * @mbg.generated
     */
    private Date planExpectEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_expect_time
     *
     * @mbg.generated
     */
    private Double planExpectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_reality_enddate
     *
     * @mbg.generated
     */
    private Date planRealityEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_reality_time
     *
     * @mbg.generated
     */
    private Double planRealityTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_reality_type
     *
     * @mbg.generated
     */
    private Integer planRealityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_reality_result
     *
     * @mbg.generated
     */
    private String planRealityResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_self_fine
     *
     * @mbg.generated
     */
    private Double planSelfFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_owner_fine
     *
     * @mbg.generated
     */
    private Double planOwnerFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_task.plan_problem
     *
     * @mbg.generated
     */
    private String planProblem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.id
     *
     * @return the value of tb_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.id
     *
     * @param id the value for tb_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_user_id
     *
     * @return the value of tb_task.plan_user_id
     *
     * @mbg.generated
     */
    public Integer getPlanUserId() {
        return planUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_user_id
     *
     * @param planUserId the value for tb_task.plan_user_id
     *
     * @mbg.generated
     */
    public void setPlanUserId(Integer planUserId) {
        this.planUserId = planUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.task_context
     *
     * @return the value of tb_task.task_context
     *
     * @mbg.generated
     */
    public String getTaskContext() {
        return taskContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.task_context
     *
     * @param taskContext the value for tb_task.task_context
     *
     * @mbg.generated
     */
    public void setTaskContext(String taskContext) {
        this.taskContext = taskContext == null ? null : taskContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_expect_result
     *
     * @return the value of tb_task.plan_expect_result
     *
     * @mbg.generated
     */
    public String getPlanExpectResult() {
        return planExpectResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_expect_result
     *
     * @param planExpectResult the value for tb_task.plan_expect_result
     *
     * @mbg.generated
     */
    public void setPlanExpectResult(String planExpectResult) {
        this.planExpectResult = planExpectResult == null ? null : planExpectResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_expect_enddate
     *
     * @return the value of tb_task.plan_expect_enddate
     *
     * @mbg.generated
     */
    public Date getPlanExpectEnddate() {
        return planExpectEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_expect_enddate
     *
     * @param planExpectEnddate the value for tb_task.plan_expect_enddate
     *
     * @mbg.generated
     */
    public void setPlanExpectEnddate(Date planExpectEnddate) {
        this.planExpectEnddate = planExpectEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_expect_time
     *
     * @return the value of tb_task.plan_expect_time
     *
     * @mbg.generated
     */
    public Double getPlanExpectTime() {
        return planExpectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_expect_time
     *
     * @param planExpectTime the value for tb_task.plan_expect_time
     *
     * @mbg.generated
     */
    public void setPlanExpectTime(Double planExpectTime) {
        this.planExpectTime = planExpectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_reality_enddate
     *
     * @return the value of tb_task.plan_reality_enddate
     *
     * @mbg.generated
     */
    public Date getPlanRealityEnddate() {
        return planRealityEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_reality_enddate
     *
     * @param planRealityEnddate the value for tb_task.plan_reality_enddate
     *
     * @mbg.generated
     */
    public void setPlanRealityEnddate(Date planRealityEnddate) {
        this.planRealityEnddate = planRealityEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_reality_time
     *
     * @return the value of tb_task.plan_reality_time
     *
     * @mbg.generated
     */
    public Double getPlanRealityTime() {
        return planRealityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_reality_time
     *
     * @param planRealityTime the value for tb_task.plan_reality_time
     *
     * @mbg.generated
     */
    public void setPlanRealityTime(Double planRealityTime) {
        this.planRealityTime = planRealityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_reality_type
     *
     * @return the value of tb_task.plan_reality_type
     *
     * @mbg.generated
     */
    public Integer getPlanRealityType() {
        return planRealityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_reality_type
     *
     * @param planRealityType the value for tb_task.plan_reality_type
     *
     * @mbg.generated
     */
    public void setPlanRealityType(Integer planRealityType) {
        this.planRealityType = planRealityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_reality_result
     *
     * @return the value of tb_task.plan_reality_result
     *
     * @mbg.generated
     */
    public String getPlanRealityResult() {
        return planRealityResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_reality_result
     *
     * @param planRealityResult the value for tb_task.plan_reality_result
     *
     * @mbg.generated
     */
    public void setPlanRealityResult(String planRealityResult) {
        this.planRealityResult = planRealityResult == null ? null : planRealityResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_self_fine
     *
     * @return the value of tb_task.plan_self_fine
     *
     * @mbg.generated
     */
    public Double getPlanSelfFine() {
        return planSelfFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_self_fine
     *
     * @param planSelfFine the value for tb_task.plan_self_fine
     *
     * @mbg.generated
     */
    public void setPlanSelfFine(Double planSelfFine) {
        this.planSelfFine = planSelfFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_owner_fine
     *
     * @return the value of tb_task.plan_owner_fine
     *
     * @mbg.generated
     */
    public Double getPlanOwnerFine() {
        return planOwnerFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_owner_fine
     *
     * @param planOwnerFine the value for tb_task.plan_owner_fine
     *
     * @mbg.generated
     */
    public void setPlanOwnerFine(Double planOwnerFine) {
        this.planOwnerFine = planOwnerFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_task.plan_problem
     *
     * @return the value of tb_task.plan_problem
     *
     * @mbg.generated
     */
    public String getPlanProblem() {
        return planProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_task.plan_problem
     *
     * @param planProblem the value for tb_task.plan_problem
     *
     * @mbg.generated
     */
    public void setPlanProblem(String planProblem) {
        this.planProblem = planProblem == null ? null : planProblem.trim();
    }
}