package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbCheck;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check
     *
     * @mbg.generated
     */
    int insert(TbCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check
     *
     * @mbg.generated
     */
    int insertSelective(TbCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check
     *
     * @mbg.generated
     */
    TbCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCheck record);

    /**
     * 根据审核状态查询所有列表
     */
    List<TbCheck> selectList(@Param("checkStatus") int checkStatus);
}