package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbMeeting;
import com.hbsd.model.sys.BaseModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    int insert(TbMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    int insertSelective(TbMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    TbMeeting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbMeeting record);

    List<TbMeeting> selectList(@Param("model") BaseModel model, @Param("keyword")String keyword);

    int queryCount(@Param("keyword")String keyword);

    /*添加会议纪要*/
    int saveMeeting(TbMeeting meeting);


    List<TbMeeting> selectListNoLogin(@Param("date") String queryDateString);

    TbMeeting selectByPrimaryKeyNoLogin(int id);
}