package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbMeetingUser;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbMeetingUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting_user
     *
     * @mbg.generated
     */
    int insert(TbMeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting_user
     *
     * @mbg.generated
     */
    int insertSelective(TbMeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting_user
     *
     * @mbg.generated
     */
    TbMeetingUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbMeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_meeting_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbMeetingUser record);

    int deleteByMeetingId(Integer meetingId);

    List<TbMeetingUser> queryBymeetingId(Integer meetingId);
}