package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbOff;
import org.springframework.stereotype.Repository;

@Repository
public interface TbOffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_off
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_off
     *
     * @mbg.generated
     */
    int insert(TbOff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_off
     *
     * @mbg.generated
     */
    int insertSelective(TbOff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_off
     *
     * @mbg.generated
     */
    TbOff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_off
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_off
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOff record);
}