package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbOvertime;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbOvertimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_overtime
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_overtime
     *
     * @mbg.generated
     */
    int insert(TbOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_overtime
     *
     * @mbg.generated
     */
    int insertSelective(TbOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_overtime
     *
     * @mbg.generated
     */
    TbOvertime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_overtime
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbOvertime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_overtime
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbOvertime record);

    List<TbOvertime> selectListByUserId(@Param("userId") int userId,@Param("keyword") String keyword);

    List<TbOvertime> selectList(@Param("keyword") String keyword);

    TbOvertime selectByPrimaryKey2(int id);
}