package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbPlanUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbPlanUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan_user
     *
     * @mbg.generated
     */
    int insert(TbPlanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan_user
     *
     * @mbg.generated
     */
    int insertSelective(TbPlanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan_user
     *
     * @mbg.generated
     */
    TbPlanUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbPlanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_plan_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbPlanUser record);


    TbPlanUser selectByPlanUserId(@Param("plan_id") Integer plan_id);
}