package com.hbsd.mapper.business;

import com.hbsd.bean.business.TbScoreRecord;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TbScoreRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score_record
     *
     * @mbg.generated
     */
    int insert(TbScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score_record
     *
     * @mbg.generated
     */
    int insertSelective(TbScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score_record
     *
     * @mbg.generated
     */
    TbScoreRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbScoreRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbScoreRecord record);

    List<TbScoreRecord> selectListByUserId(@Param("userId") int userId);

    List<TbScoreRecord> selectList();

    int  selectCount();

    int  selectCountByUserId(@Param("userId") int userId);

    TbScoreRecord selectByPrimaryKey2(Integer id);

    int sumTbScore(@Param("userId") int userId,@Param("year") int year);
}